# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
  include:
  - python: pypy
    env: TOX_ENV=pypy
  - python: 3.6
    env: TOX_ENV=flake8

install:
- pip install tox

script:
- bash tests/images/sshd_image/run_sshd_image.sh
- tox -e $TOX_ENV

before_cache:
- rm -rf $HOME/.cache/pip/log

cache:
  directories:
  - $HOME/.cache/pip
